#!/bin/bash

function package_install_cmd {
    PKGCMD=$1
    PKGNAME=$2
    PKGDESC=$3

    $PKGCMD &>/dev/null
    if [ $? -gt 0 ] ; then
      msg_info "$PKGDESC not installed. Installing now..."
      apt-get --force-yes -y install $PKGNAME
      $PKGCMD &>/dev/null
      if [ $? -eq 0 ] ; then
        msg_ok "$PKGDESC installed."
      else
        msg_fail "$PKGDESC installation failed!"
        die 1 "I could NOT install $PKGDESC. Check your sources.list and/or Internet access or try to do it manually!"
      fi
    else
      msg_ok "$PKGDESC installed."
    fi
}

function package_install {
    PKGNAME=$1
    PKGDESC=$2

    dpkg -l | awk '{print $2}' | grep ^$PKGNAME$ &>/dev/null
    if [ $? -gt 0 ] ; then
      msg_info "$PKGDESC not installed. Installing now..."
      apt-get --force-yes -y install $PKGNAME
      dpkg -l | awk '{print $2}' | grep $PKGNAME &>/dev/null
      if [ $? -eq 0 ] ; then
        msg_ok "$PKGDESC installed."
      else
        msg_fail "$PKGDESC installation failed!"
        die 1 "I could NOT install $PKGDESC. Check your Internet access or try to do it manually!"
      fi
    else
      msg_ok "$PKGDESC installed."
    fi
}

function cmd_if_0_info
{
    CMDCHECK=$1
    CMD=$2
    ELSEMSG=$3

    eval $CMDCHECK &>/dev/null
    if [ $? -eq 0 ] ; then
      cmd "$CMD"
    else
      msg_info "$ELSEMSG"
    fi
}

function cmd_if_n0_info
{
    CMDCHECK=$1
    CMD=$2
    ELSEMSG=$3

    eval $CMDCHECK &>/dev/null
    if [ $? -gt 0 ] ; then
      cmd "$CMD"
    else
      msg_info "$ELSEMSG"
    fi
}
